apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aia-min-side-ssr
  namespace: paw
  labels:
    team: paw
spec:
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env: # Add your environment variables here
    - name: SIDE_2_URL
      value: https://www.nav.no/arbeidssoekerregisteret
