version: 2
updates:
  # Enable version updates for pnpm
  - package-ecosystem: "pnpm"
    directory: "/"
    # Check the pnpm registry for updates once a week
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7