version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      aksel:
        patterns:
          - "@navikt/aksel-*"
          - "@navikt/ds-*"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"