apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aia-min-side-ssr
  namespace: paw
  labels:
    team: paw
spec:
  tokenx:
    enabled: true
  image: {{ image }}
  ingresses:
    - https://aia-min-side-ssr.ansatt.dev.nav.no
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
    outbound:
      rules:
        - application: paw-arbeidssoekerregisteret-api-oppslag-v2
        - application: paw-arbeidssoekerregisteret-api-bekreftelse
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env: # Add your environment variables here
    - name: SIDE_2_URL
      value: https://www.ansatt.dev.nav.no/arbeidssoekerregisteret
    - name: ARBEIDSSOEKERPERIODER_AGGREGERT_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag-v2/api/v1/arbeidssoekerperioder-aggregert?siste=true
    - name:  ARBEIDSSOKERREGISTERET_OPPSLAG_CLIENT_ID
      value: dev-gcp:paw:paw-arbeidssoekerregisteret-api-oppslag-v2
    - name: TILGJENGELIGE_BEKREFTELSER_URL
      value: http://paw-arbeidssoekerregisteret-api-bekreftelse/api/v1/tilgjengelige-bekreftelser
    - name: BEKREFTELSE_API_CLIENT_ID
      value: dev-gcp:paw:paw-arbeidssoekerregisteret-api-bekreftelse
